In [4]:
import sys
import numpy as np

In [5]:
np.array([1, 2, 3, 4])


array([1, 2, 3, 4])

In [8]:

array([1, 2, 3, 4])

<class 'NameError'>: name 'array' is not defined

In [6]:
a = np.array([1, 2, 3, 4])

In [7]:
b = np.array([0, .5, 1, 1.5, 2])

In [9]:
a[0], a[1]

(1, 2)

In [10]:
a[0:]

array([1, 2, 3, 4])

In [11]:
a[1:3]

array([2, 3])

In [12]:
a[1:-1]

array([2, 3])

In [13]:
a[::2]

array([1, 3])

In [14]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [16]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
a.dtype

dtype('int32')

In [19]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [20]:
b.dtype

dtype('float64')

In [21]:

dtype('float64')

<class 'NameError'>: name 'dtype' is not defined

In [22]:

np.array([1, 2, 3, 4], dtype=np.float)

<class 'AttributeError'>: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [23]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [25]:
c = np.array(['a', 'b', 'c'])

In [26]:
c.dtype

dtype('<U1')

In [27]:
d = np.array([{'a': 1}, sys])

In [28]:
d.dtype

dtype('O')

In [29]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [30]:
A.shape

(2, 3)

In [31]:
A.ndim

2

In [32]:
A.size

6

In [33]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])


In [34]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [35]:
B.shape

(2, 2, 3)

In [36]:
B.ndim

3

In [37]:
B.size

12

In [41]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

<class 'ValueError'>: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [39]:
C.dtype

<class 'NameError'>: name 'C' is not defined

In [40]:
C.shape

<class 'NameError'>: name 'C' is not defined

In [42]:
C.size

<class 'NameError'>: name 'C' is not defined

In [43]:
type(C[0])

<class 'NameError'>: name 'C' is not defined

In [44]:
A = np.array([
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [45]:
A[1]

array([4, 5, 6])

In [46]:
A[1][0]

4

In [47]:
A[1][0]

4

In [48]:
A[1, 0]

4

In [49]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [51]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [52]:
A[:2, 2:]

array([[3],
       [6]])

In [ ]:
A

In [53]:
A[1] = np.array([10, 10, 10])

In [54]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [55]:
A[2] = 99

In [56]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [57]:
a = np.array([1, 2, 3, 4])

In [58]:
a.sum()

10

In [59]:
a.mean()

2.5

In [60]:
a.mean()

2.5

In [61]:
a.mean()

2.5

In [62]:
a.std()

1.118033988749895

In [63]:
a.var()

1.25

In [64]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [65]:
A.sum()

45

In [66]:
A.mean()

5.0

In [67]:
A.std()

2.581988897471611

In [68]:
A.sum(axis=0)

array([12, 15, 18])

In [69]:

array([12, 15, 18])

<class 'NameError'>: name 'array' is not defined

In [70]:
A.mean(axis=0)

array([4., 5., 6.])

In [72]:
A.mean(axis=1)

array([2., 5., 8.])

In [73]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [74]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [75]:
a = np.arange(4)

In [76]:
a

array([0, 1, 2, 3])

In [77]:
a + 10

array([10, 11, 12, 13])

In [78]:
a * 10

array([ 0, 10, 20, 30])

In [79]:
a

array([0, 1, 2, 3])

In [80]:
a += 100

In [81]:
a

array([100, 101, 102, 103])

In [82]:
l = [0, 1, 2, 3]

In [83]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [84]:
a = np.arange(4)

In [85]:
a

array([0, 1, 2, 3])

In [86]:
b = np.array([10, 10, 10, 10])

In [87]:
b

array([10, 10, 10, 10])

In [88]:
a = np.arange(4)

In [89]:
a

array([0, 1, 2, 3])

In [90]:
b = np.array([10, 10, 10, 10])

In [91]:
b

array([10, 10, 10, 10])

In [92]:
a * b

array([ 0, 10, 20, 30])

In [93]:
a = np.arange(4)

In [94]:
a


array([0, 1, 2, 3])

In [95]:
a[0], a[-1]

(0, 3)

In [96]:
a[[0, -1]]

array([0, 3])

In [97]:
a[[True, False, False, True]]

array([0, 3])

In [98]:
a

array([0, 1, 2, 3])

In [99]:
a >= 2

array([False, False,  True,  True])

In [100]:
a[a >= 2]

array([2, 3])

In [101]:
a.mean()

1.5

In [102]:
a[a > a.mean()]

array([2, 3])

In [103]:
a[~(a > a.mean())]

array([0, 1])

In [104]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [105]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [106]:
A = np.random.randint(100, size=(3, 3))

In [107]:
A

array([[45, 69, 80],
       [50, 98, 36],
       [66, 24, 68]])

In [108]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([45, 80, 98, 66, 68])

In [109]:
A > 30

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [110]:
A[A > 30]

array([45, 69, 80, 50, 98, 36, 66, 68])

In [111]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [112]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [113]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [114]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [115]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [116]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [118]:
sys.getsizeof(1)

16

In [119]:
sys.getsizeof(10**100)


60

In [120]:
np.dtype(int).itemsize

4

In [121]:
np.dtype(np.int8).itemsize


1

In [122]:
np.dtype(float).itemsize

8

In [123]:
sys.getsizeof([1])

32

In [124]:
np.array([1]).nbytes

4

In [125]:

l = list(range(100000))

In [126]:
a = np.arange(100000)

In [127]:
%time np.sum(a ** 2)
CPU times: user 1.06 ms, sys: 279 µs, total: 1.34 ms
Wall time: 701 µs

<class 'SyntaxError'>: invalid syntax (<ipython-input-127-4b5a8f59e653>, line 2)

In [128]:
%time sum([x ** 2 for x in l])
CPU times: user 36.1 ms, sys: 0 ns, total: 36.1 ms
Wall time: 35.5 ms

<class 'SyntaxError'>: invalid syntax (<ipython-input-128-a83b5303608e>, line 2)

In [129]:
np.random.random(size=2)

array([0.41122883, 0.00179418])

In [130]:
np.random.normal(size=2)

array([0.76149889, 0.9380077 ])

In [131]:
np.random.rand(2, 4)

array([[0.60598476, 0.60131974, 0.52486566, 0.03070968],
       [0.75157469, 0.67905113, 0.53846936, 0.13340596]])

In [132]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [134]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [135]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [136]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [137]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [138]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [139]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [140]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [141]:
np.zeros((3, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [142]:
np.zeros((3, 3), dtype=np.int)

<class 'AttributeError'>: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [143]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [144]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [145]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [146]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [147]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [148]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [149]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [150]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [151]:
"Hello World"[6]

'W'